### ISSUE TITLE
Revolve 2D MAST-U mesh toroidally to get a 3D mesh

### ISSUE THREAD

**Issue by jwscook** [UKAEA-Edge-Code/EdgeCodeRequirements#21]

**Comment by jwscook** [comment]
@futtersack please feel free to add here context around inaccurate 3D interpolation of the 2D magnetic field.

**Comment by futtersack** [comment]
Tried to draw something if it makes things more clear ?
We have B finely defined on RZ plane. Currently I export the projections onto xyz planes in a B.pts file at 24 toroidal locations (500Mo). but the cells between those slices get interpolated in a "straight" line (beside taking 5mn per composant Bx, By, Bz from the large file).
![2DequTo3D](https://github.com/UKAEA-Edge-Code/EdgeCodeRequirements/assets/5637127/52cce894-9520-4aa3-b78a-4a1c43ecb1c0)

**Comment by JamesEdgeley** [comment]
This is the full mesh that Romain produced
![Image](https://github.com/UKAEA-Edge-Code/EdgeCodeRequirements/assets/16880076/72c2d321-1dd4-4414-8b8d-a4349934ed23)


I've also made a NekMesh module to revolve a 2D Nektar++ mesh toroidally.  This is the edge region from the 2D MASTU example:
![Image](https://github.com/UKAEA-Edge-Code/EdgeCodeRequirements/assets/16880076/70d815ae-f5dd-43f5-90a4-fee4c5a8fcff)

**Comment by cmacmackin** [comment]
@futtersack Does this address your issues, or would it still be helpful for me to modify your script?

**Comment by JamesEdgeley** [comment]
~~Link to NekMesh revolve [MR](https://gitlab.nektar.info/nektar/nektar/-/merge_requests/1825)~~
Now merged

**Comment by jwscook** [comment]
Now we need to run a simulation, ideally (ambipolar) diffusion on these meshes.

**Comment by jwscook** [comment]
Done!
